feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name = 'detail'),
    path('post/', AddPostView.as_view(), name= 'post'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField()

    def __str__(self):
        return self.text

feed/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()

feed/views.py
from typing import Any
from django.contrib import messages
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.views.generic import TemplateView, DetailView, FormView
from .models import Post
from .forms import PostForm


class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context
    
class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post

class AddPostView(FormView):
    template_name= 'new_post.html'
    form_class = PostForm
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request,  *args, **kwargs)

    def form_valid(self, form):
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image = form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your Post Was Successful')
        return super().form_valid(form)

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Image Sharer{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</head>

<body>
    
    {% if messages %}
    {% for message in messages %}
    
    <div class="bg-{% if message.tags%}{{ message.tags }}{% else %}success{% endif %} bt-gradient text-center text-white py-4">{{ message }}</div>
    {% endfor %}
    {% endif %}
    
    
    {% include "includes/navbar.html" %}
   
  
    <div class="container">
    {% block body %} {% endblock%}
</div>
</body>

</html>

templates/detail.html
{% extends "base.html" %}

{% block title%} Detail View{%endblock%}

{% block body %}

<a href="{% url 'feed:index' %}">&larr; Go Back</a>

<h3>{{ object.text }}</h3>

<div class="col-sm-10 offset-sm-1 pt-5">
<img src="{{object.image.url}}" width="100%" height="auto" class="img-fluid">

</div>
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Image Sharer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feed:post' %}">Add new image</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/index.html
{% extends "base.html" %} {% load thumbnail %} {% block title %}Homepage of
Image Sharer {% endblock%} {% block body %}

<br />

<div class="row">
  {% for post in posts %}
  <div class="col-sm-6 col-md-3">
    <div class="card mb-4" style="width: 14rem" >
      {% thumbnail post.image "300x300" crop="center" as im %}
      <img src="{{ im.url }}" class="card-img-top" />
      {% endthumbnail %}
      <div class="card-body">
        <h5 class="card-title">{{ post.text }}</h5>
        <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary"
          >Details</a
        >
      </div>
    </div>
  </div>

  {% empty %}
  <div class="col-sm-6 offset-3 text-center py-5 my-5">
    <h3>Welcome</h3>
    <p>Upload an Image!</p>
    <a href="{% url 'feed:post' %}" class="btn btn-success">Upload an Image</a>
  </div>
  {% endfor %}
</div>
{% endblock%}

templates/new_post.html
{% extends "base.html" %}

{% block title%} Upload A Image{%endblock%}

{% block body %}

<form method="post" action="" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
<h2>
Upload an Image
</h2>
    {% csrf_token%}
{{ form.as_ul}}


<div>
    <button type="submit" class="btn btn-success my-2">Submit Form</button>
</div>

</form>
{% endblock %}